
services:
  apache:
    build: apache-php-lamp
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./prestashop_8.2.1_lamp:/app
      - ./apache-php-lamp/vhost-apache.conf:/etc/apache2/sites-enabled/vhost-apache.conf
      - ./apache-php-lamp/php.ini:/etc/php/8.1/apache2/php.ini
      - ./certs:/etc/apache2/certs
    networks:
      redelamplemp:
        aliases:
          - test.lan
          - www.test.lan
    env_file:
      - .env.dev

  basededatos:
    image: mysql:5.7
    volumes:
      - datos:/var/lib/mysql
    env_file:
      - .env.dev

    networks:
      redelamplemp:

  cliente:
    hostname: cliente
    image: brunosct/debian12-cliente-firefox
    networks:
      - redelamplemp
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  

volumes:
  datos:

networks:
  redelamplemp:

