services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./prestashop_8.2.1:/app
      #vhost nginx
      - ./nginx-lemp/vhost-nginx.conf:/etc/nginx/conf.d/vhost-nginx.conf
      #certificados
      - ./certs:/etc/ssl
    networks:
      redelamplemp:
        aliases:
          - test.lan
    env_file:
      - .env.prod
