version: "3.7"

services:
  apache:
    build: apache-php-lamp
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./prestashop_8.2.1:/app
      - ./apache-php-lamp/vhost-apache.conf:/etc/apache2/sites-enabled/vhost-apache.conf
      - ./apache-php-lamp/php.ini:/etc/php/8.1/apache2/php.ini
      - ./certs:/etc/apache2/certs

    env_file:
      - .env.prod


